# Generated by Django 6.0 on 2025-12-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationbooking',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='installationbooking',
            name='installation_type',
            field=models.CharField(choices=[('Solar Panel', 'Solar Panel Installation'), ('EV Charger', 'EV Charger Installation'), ('Battery Storage', 'Battery Storage Setup'), ('maintenance', 'General Maintenance'), ('inverters', 'Inverter Installation'), ('others', 'other installations')], max_length=50),
        ),
    ]
